### ISSUE TITLE
Error while trying to install with pull-through cache

### ISSUE THREAD

**Issue by dkliban** [pulp/pulp_gem#209]
**Version**
Please provide the versions of the pulpcore and pulp_gem packages in use, and how they are installed.  If you are using Pulp via Katello, please provide the Katello version.

**Describe the bug**
Error when using pull-through cache

**To Reproduce**

```
pulp gem remote create --name gem --url https://index.rubygems.org/

pulp gem distribution create --name foo --base-path foo --remote gem

gem install --clear-sources --source https://env-ephemeral-.apps.crc-eph.r9lp.p1.openshiftapps.com/pulp/content/foo/foo/ panda

$ gem install --clear-sources --source https://env-ephemeral-6xdm69.apps.crc-eph.r9lp.p1.openshiftapps.com/pulp/content/foo/foo/ panda
Fetching panda-1.6.1.gem
Fetching ruby-hmac-0.4.0.gem
Fetching ruby-hmac-0.4.0.gem
#<Thread:0x00007f6129fb5d38 /usr/share/rubygems/rubygems/request_set.rb:167 run> terminated with exception (report_on_exception is true):
/usr/share/rubygems/rubygems/request.rb:249:in `rescue in perform_request': too many connection resets (https://env-ephemeral-6xdm69.apps.crc-eph.r9lp.p1.openshiftapps.com/pulp/content/foo/foo/gems/ruby-hmac-0.4.0.gem) (Gem::RemoteFetcher::FetchError)
        from /usr/share/rubygems/rubygems/request.rb:193:in `perform_request'
        from /usr/share/rubygems/rubygems/request.rb:154:in `fetch'
        from /usr/share/rubygems/rubygems/remote_fetcher.rb:309:in `request'
        from /usr/share/rubygems/rubygems/remote_fetcher.rb:209:in `fetch_http'
        from /usr/share/rubygems/rubygems/remote_fetcher.rb:248:in `fetch_path'
        from /usr/share/rubygems/rubygems/remote_fetcher.rb:285:in `cache_update_path'
        from /usr/share/rubygems/rubygems/remote_fetcher.rb:146:in `download'
        from /usr/share/rubygems/rubygems/source.rb:208:in `download'
        from /usr/share/rubygems/rubygems/resolver/specification.rb:112:in `download'
        from /usr/share/rubygems/rubygems/request_set.rb:173:in `block (2 levels) in install'
/usr/share/ruby/net/protocol.rb:237:in `rbuf_fill': end of file reached (EOFError)
        from /usr/share/ruby/net/protocol.rb:199:in `readuntil'
        from /usr/share/ruby/net/protocol.rb:209:in `readline'
        from /usr/share/ruby/net/http/response.rb:605:in `read_chunked'
        from /usr/share/ruby/net/http/response.rb:575:in `block in read_body_0'
        from /usr/share/ruby/net/http/response.rb:568:in `inflater'
        from /usr/share/ruby/net/http/response.rb:573:in `read_body_0'
        from /usr/share/ruby/net/http/response.rb:344:in `read_body'
        from /usr/share/rubygems/rubygems/request.rb:208:in `block in perform_request'
        from /usr/share/ruby/net/http.rb:1873:in `block in transport_request'
        from /usr/share/ruby/net/http/response.rb:301:in `reading_body'
        from /usr/share/ruby/net/http.rb:1872:in `transport_request'
        from /usr/share/ruby/net/http.rb:1826:in `request'
        from /usr/share/rubygems/rubygems/request.rb:202:in `perform_request'
        from /usr/share/rubygems/rubygems/request.rb:154:in `fetch'
        from /usr/share/rubygems/rubygems/remote_fetcher.rb:309:in `request'
        from /usr/share/rubygems/rubygems/remote_fetcher.rb:209:in `fetch_http'
        from /usr/share/rubygems/rubygems/remote_fetcher.rb:248:in `fetch_path'
        from /usr/share/rubygems/rubygems/remote_fetcher.rb:285:in `cache_update_path'
        from /usr/share/rubygems/rubygems/remote_fetcher.rb:146:in `download'
        from /usr/share/rubygems/rubygems/source.rb:208:in `download'
        from /usr/share/rubygems/rubygems/resolver/specification.rb:112:in `download'
        from /usr/share/rubygems/rubygems/request_set.rb:173:in `block (2 levels) in install'
Fetching multi_json-1.15.0.gem
ERROR:  While executing gem ... (Gem::RemoteFetcher::FetchError)
    too many connection resets (Gem::RemoteFetcher::FetchError)
        /usr/share/rubygems/rubygems/request.rb:249:in `rescue in perform_request'
        /usr/share/rubygems/rubygems/request.rb:193:in `perform_request'
        /usr/share/rubygems/rubygems/request.rb:154:in `fetch'
        /usr/share/rubygems/rubygems/remote_fetcher.rb:309:in `request'
        /usr/share/rubygems/rubygems/remote_fetcher.rb:209:in `fetch_http'
        /usr/share/rubygems/rubygems/remote_fetcher.rb:248:in `fetch_path'
        /usr/share/rubygems/rubygems/remote_fetcher.rb:285:in `cache_update_path'
        /usr/share/rubygems/rubygems/remote_fetcher.rb:146:in `download'
        /usr/share/rubygems/rubygems/source.rb:208:in `download'
        /usr/share/rubygems/rubygems/resolver/specification.rb:112:in `download'
        /usr/share/rubygems/rubygems/request_set.rb:173:in `block (2 levels) in install'
```

**Expected behavior**
panda gem is installed

**Additional context**

The following appears in the content app logs:

```
[2024-01-29 19:41:36 +0000] [11] [ERROR] Error handling request
Traceback (most recent call last):
File "/usr/local/lib64/python3.8/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request
resp = await request_handler(request)
File "/usr/local/lib64/python3.8/site-packages/aiohttp/web_app.py", line 543, in _handle
resp = await handler(request)
File "/usr/local/lib64/python3.8/site-packages/aiohttp/web_middlewares.py", line 114, in impl
return await handler(request)
File "/usr/local/lib/python3.8/site-packages/pulpcore/content/authentication.py", line 48, in authenticate
return await handler(request)
File "/usr/local/lib/python3.8/site-packages/pulpcore/content/instrumentation.py", line 230, in middleware
resp = await handler(request)
File "/usr/local/lib/python3.8/site-packages/pulpcore/cache/cache.py", line 352, in cached_function
response = await self.make_entry(
File "/usr/local/lib/python3.8/site-packages/pulpcore/cache/cache.py", line 395, in make_entry
response = await handler(*args, **kwargs)
File "/usr/local/lib/python3.8/site-packages/pulpcore/content/handler.py", line 257, in stream_content
return await self._match_and_stream(path, request)
File "/usr/local/lib/python3.8/site-packages/pulpcore/content/handler.py", line 764, in _match_and_stream
return await self._stream_remote_artifact(
File "/usr/local/lib/python3.8/site-packages/pulpcore/content/handler.py", line 1112, in _stream_remote_artifact
await asyncio.shield(
File "/usr/local/lib/python3.8/site-packages/asgiref/sync.py", line 479, in __call__
ret: _R = await loop.run_in_executor(
File "/usr/lib64/python3.8/concurrent/futures/thread.py", line 57, in run
result = self.fn(*self.args, **self.kwargs)
File "/usr/local/lib/python3.8/site-packages/asgiref/sync.py", line 538, in thread_handler
return func(*args, **kwargs)
File "/usr/local/lib/python3.8/site-packages/pulpcore/content/handler.py", line 883, in _save_artifact
content = c_type.init_from_artifact_and_relative_path(artifact, rel_path)
File "/usr/local/lib/python3.8/site-packages/pulp_gem/app/models.py", line 67, in init_from_artifact_and_relative_path
gem_info, spec_data = analyse_gem(artifact.file)
File "/usr/local/lib/python3.8/site-packages/pulp_gem/specs.py", line 354, in analyse_gem
gem_info["dependencies"] = {
File "/usr/local/lib/python3.8/site-packages/pulp_gem/specs.py", line 355, in <dictcomp>
dep.attributes["@name"]: dep.attributes["@requirement"].to_s() for dep in dependencies
KeyError: '@requirement'
```

**Comment by mdellweg** [comment]
https://docs.ruby-lang.org/en/master/Gem/Dependency.html  See the source code of `requirement()` there,
